language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: b/GH/OJ70O+BSLNjmL+x5gEMo2hP5WTi6p6VLV12V9E4z6HMsaqXulq+DUl/xedBVdPjv4rmkyXOKMy14Go/1izph3XIEjpZZupvUifqR5gNM/ZU5bssFWOYh4O8IH1csTQnIJFK9y/GrOpxPVmV7wjHcrMIi5sR2lc2fneQ2oWE6pZurH5bIPgeer+LN2zDuhglWNw+85WB9vBZGfgrlUPM3HkJ6NLC/8q3D3Qce0JJRZ/rouYGg9Erfgn4nj00bXJB/crotlHiOm1hEZ73jsOiw3MMZntYUlZSW00o5J4s6r9GAy0KQY/lQj6rijLClkfdOFXcITw2odqEOSzrcr0gdxVvf2Fas1ndfG2ByIRqfSnftE6xBg8cJa2qktAW9Cbv4IuPoreMIDqYmuiY2DPQLduuUdmV6GHpo461tla4qCBxCj9lTcbGXCjcao/mLqVaHBgSLgbUmR/DuuTuhot9HM2ZmRtG5MNyUT4RF3Y56geXe0zqijVE+PGQGUBA4+N7eMov+a3fYb5lhVes0ng/CDEjZihuSi/MxHCgpiYxC5bnTNcmyLFnafb93bZbJ0vVLFTH9yUNLSEkV2Y/6mUBAg0ghE9ScqWyhBeCIQc3sHp8PNEGWMrW+gunSuQeKfYTGDO0iZokW+0WIZXclTknv9ZUhwUXDp3sbzOdD3Y=
